### ISSUE TITLE
Support multiple citations for datasets

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1303]
Some datasets have multiple citations and sometimes we want to combine multiple datasets into a single dataset (see #1297). It would be nice to be able to support this by effectively displaying more than one citation. We'll need to check if there are issues with the Frictionless Data specs, but from a first glance it looks like `citation` isn't actually in their specs (surprisingly) so we can probably do whatever we want.

**Comment by henrykironde** [comment]
We can use a dictionary
```yaml
  "citation": [
    {
      "table1": "citation for table one.",
      "table2": "citation for table two."
    }
  ]
```

or we could just provide a list of the all the citations and leave it to the user to identify which citation belongs to which data

```yaml
  "citation": [
         "citation for table one.",
         "citation for table two.",
  ]
```
