### ISSUE TITLE
Update codecov to action stage in workflows

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1632]
[![codecov.io](https://codecov.io/github/weecology/retriever/coverage.svg?branch=main)](https://codecov.io/github/weecology/retriever?branch=main)
- remove the Codecov code coverage configuration file codecov.yml
- Add action step in python-package.yml after tests

```yaml
    - name: Run pytest
        run: |
        pytest -v -k "not test_geojson2csv  and not test_mysql_integration" --cov=retriever --cov-report=xml
        flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90 2>&1
        yapf -d --recursive ./retriever/ --style=.style.yapf 2>&1
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} not required for public project
        file: ./coverage.xml
```
