### ISSUE TITLE
Publish 2.1 release at JOSS

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#534]
The [Journal of Open Source Software](http://joss.theoj.org/) is a really cool initiative to help provide review and credit for software in an academic context. Once we're at 2.0 we should submit there.

**Comment by zhangcandrew** [comment]
So it looks like to get this done we need a .md that has a format shown below, with the main points being: 
* A list of the authors of the software
* Author affiliations
* A short summary describing the high-level functionality of the software
* A list of key references including a link to the software archive


```
---
  title: 'Fidgit: An ungodly union of GitHub and figshare'
  tags:
    - example
    - tags
    - for the paper
  authors:
   - name: Arfon M Smith
     orcid: 0000-0000-0000-1234
     affiliation: 1
   - name: Mickey Mouse
     orcid: 0000-0000-0000-1234
     affiliation: 2
  affiliations:
   - name: Space Telescope Science Institute
     index: 1
   - name: Disney Inc.
     index: 2
  date: 14 February 2016
  bibliography: paper.bib
  ---

  # Summary

  This is a proof of concept integration between a GitHub [@GitHub] repo and figshare
  [@figshare] in an effort to get a DOI for a GitHub repository. When a repository is
  tagged for release on GitHub, Fidgit [@Fidgit] will import the release into figshare
  thus giving the code bundle a DOI. In a somewhat meta fashion, Fidgit is publishing
  itself to figshare with DOI 'http://dx.doi.org/10.6084/m9.figshare.828487'
  [@figshare_archive].

  -![Fidgit deposited in figshare.](figshare_article.png)

  # References
```

Do we have anything like this already? I can start doing the writeup from scratch too
